application: your_application
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
    
- url: /
  script: migraciones.app
    
- url: /js
  static_dir: js

- url: /css
  static_dir: css

libraries:
  - name: webapp2
    version: "2.5.2"

